### ISSUE TITLE
Can you make it so it opens the default set alarm, instead of calender?

### ISSUE THREAD

**Issue by lovebes** [omatt/canicoffee#1]
Love your app! I wanted to make one like such ever since knowing about the Circadian rhythm/cortisol.
Two issues.
1. How did you calculate to change the coffee intake depending on wake time? The linked blog post at the website doesn't have that information so I was curious.
2. As the subject - I find it more useful if the alarm is set instead of the calendar. 

If you have free time that is - otherwise I'll try to fork/modify when I have time (although my extent of Android app dev is Cordova.. I can't imagine doing this with Android Studio ;( )

Thanks!

**Comment by omatt** [comment]
Fix committed [here](https://github.com/omatt/canicoffee/commit/182236749ab9342ffe3694ed180071dd8a2ba53c). Now uses AlarmClock instead of Calendar.

The calculation of intake is based from keikun17's [canicoffee site](https://keikun17.github.io/canicoffee/). First intake is 0330H after waking up, second is 0730H after waking up.
